<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {


        // 2. Metric: Purchases Today
        $todayPurchases = \App\Models\Transaction::where('type', 'purchase')
            ->whereDate('transaction_date', today())
            ->sum('total_amount');

        // 3. Metric: Net Revenue (Uang Masuk Bersih Today)
        // Gross Payments - Change/Excess for debts paid today
        $grossPayments = \App\Models\Payment::whereDate('payment_date', today())->sum('amount');

        // Calculate total excess (change) for debts that had payments today
        $debtsWithPaymentsToday = \App\Models\Debt::whereHas('payments', function ($q) {
            $q->whereDate('payment_date', today());
        })->get();

        $totalChange = 0;
        foreach ($debtsWithPaymentsToday as $debt) {
            if ($debt->amount_paid > $debt->amount_total) {
                // Only consider change generated by *today's* payments
                // For simplicity in this context, we assume all change happens on the final payment which is today
                $totalChange += ($debt->amount_paid - $debt->amount_total);
            }
        }

        $todayPaid = $grossPayments - $totalChange;

        // 4. Daily Status Breakdown (Paid, Unpaid, Partial)
        $todayDebts = \App\Models\Debt::whereDate('created_at', today())->get();

        $statusMetrics = [
            'paid' => [
                'count' => $todayDebts->where('status', 'paid')->count(),
                'cash_in' => $todayDebts->where('status', 'paid')->sum('amount_total'), // Use amount_total to exclude change
                'outstanding' => 0 // Fully paid
            ],
            'unpaid' => [
                'count' => $todayDebts->where('status', 'unpaid')->count(),
                'cash_in' => $todayDebts->where('status', 'unpaid')->sum('amount_paid'),
                'outstanding' => $todayDebts->where('status', 'unpaid')->sum(fn($d) => $d->amount_total - $d->amount_paid)
            ],
            'partial' => [
                'count' => $todayDebts->where('status', 'partial')->count(),
                'cash_in' => $todayDebts->where('status', 'partial')->sum('amount_paid'),
                'outstanding' => $todayDebts->where('status', 'partial')->sum(fn($d) => $d->amount_total - $d->amount_paid)
            ]
        ];

        return view('dashboard', compact('todayPurchases', 'todayPaid', 'statusMetrics'));
    }
}
